### PR TITLE
fix: mkdocs doesnt work with 3.10.0 python

### PR DESCRIPTION
**Pull request by pasha-codefresh**
Python just pushed new version 3.10.0 that cause mkdocs be broken. For unblock contributors I suggest use fixed version until understand and fix an issue 

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.0/x64/bin/mkdocs", line 5, in <module>
    from mkdocs.__main__ import cli
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/mkdocs/__main__.py", line 16, in <module>
    from mkdocs import config                                 # noqa: E402
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/mkdocs/config/__init__.py", line 2, in <module>
    from mkdocs.config.defaults import DEFAULT_SCHEMA
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/mkdocs/config/defaults.py", line 1, in <module>
    from mkdocs.config import config_options
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 2, in <module>
    from collections import Sequence, namedtuple
ImportError: cannot import name 'Sequence' from 'collections' (/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/collections/__init__.py)
```

https://github.com/argoproj/argo-cd/runs/3968380676?check_suite_focus=true
https://github.com/argoproj/argo-cd/runs/3968402046?check_suite_focus=true

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
LGTM
