### ISSUE TITLE
ComparsionError when using networking.k8s.io/v1 Ingress

### ISSUE THREAD

**Issue by Prototik** [argoproj/argo-cd#4358]
**Describe the bug**

I tried to manage project that defined Ingress from `networking.k8s.io/v1` api group (k8s 1.19).
Initial sync is ok, but I cannot sync any more times because of following error:
```
ComparisonError
failed to convert *unstructured.Unstructured to *v1beta1.Ingress: no kind "Ingress" is registered for version "networking.k8s.io/v1" in scheme "pkg/runtime/scheme.go:101"
```

**To Reproduce**
Just create any networking.k8s.io/v1 Ingress within 1.19 cluster

**Expected behavior**
ArgoCD works with v1 Ingress

**Version**
1.7.5

**Comment by alexmt** [comment]
Probably fixed by https://github.com/argoproj/gitops-engine/pull/139

**Comment by Prototik** [comment]
I don't think so, I suppose error throws from (here)[https://github.com/argoproj/argo-cd/blob/14fa7f954c1d2e9b4b6e5572e8fab7861958c7bf/controller/cache/info.go#L106]

In v1 Ingress there is no field `serviceName`, but object `service` with nested field `name`

**Comment by Prototik** [comment]
That's fixed by 3ae1d13dfd541c34a2b970b7a6d8f32f2369d31a

**Comment by alexmt** [comment]
thank you for updating the issue @Prototik !

**Comment by kingdonb** [comment]
I still get comparisonerror, is this change in a release? (It seems by now it would be, there have been a couple of releases since Oct 14, but I can't find it mentioned in any release notes.)

**Comment by jshin47** [comment]
I also still have the same issue after upgrading to the manifest from tag 1.7.0

**Comment by avdhoot** [comment]
@alexmt Even after updating argocd to 1.7.10 still facing the same issue.

**Comment by tsde** [comment]
@alexmt Same issue here as well on version 1.7.10. Maybe the fix is still not included in a release ?

**Comment by avdhoot** [comment]
As temp solution we are using `argoproj/argocd:latest` cc @tsde @jshin47

**Comment by tsde** [comment]
Thanks for the tip @avdhoot 
I see that v1.8 is on its way and may include the fix. Though having confirmation here would be great ;)

**Comment by tsde** [comment]
@kingdonb @avdhoot @jshin47 I've just tested version 1.8.1 and this is now fixed (version 1.8.0 should be fine too)

**Comment by kingdonb** [comment]
Awesome, thanks 👍 confirmed on my end, I am in business now with
networking v1 ingresses and argo 1.8.1

 tsde wrote:

> @kingdonb <https://github.com/kingdonb> @avdhoot
> <https://github.com/avdhoot> @jshin47 <https://github.com/jshin47> I've
> just tested version 1.8.1 and this is now fixed (version 1.8.0 should be
> fine too)
>
>

**Comment by bchrobot** [comment]
We are encountering this in v2.1.3.

**Comment by jdmulloy** [comment]
Seeing this on 2.2.3 with K8s 1.20. This is not resolved.

```
{
    "Version": "v2.2.3+987f665",
    "BuildDate": "2022-01-18T17:53:49Z",
    "GitCommit": "987f6659b88e656a8f6f8feef87f4dd467d53c44",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.11",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.7.1+g1d11fcb",
    "KubectlVersion": "v0.22.2",
    "JsonnetVersion": "v0.17.0"
}

**Comment by jdmulloy** [comment]
I figured out my issue. Somewhere in upgrading ArgoCD switched from using a Deployment to using a StateFul set and upgrading via ArgoCD didn't delete the old Deployment, so it ended up abandoned. So we had a 1.7.8 application controller and a 2.2.3 application controller running at the same time, fighting with each other. If Google bring you here try running the following.

`kubectl get pods`

Mine looked like this. There should only be one "application-controller". 5c5488c47d-vgrkj is the old one that shouldn't be there
```
$ k get pods
NAME                                                 READY   STATUS    RESTARTS   AGE
argocd-application-controller-0                      1/1     Running   0          7d2h
argocd-application-controller-5c5488c47d-vgrkj       1/1     Running   0          10d
argocd-dex-server-6fb7bd4d7-sgdjf                    1/1     Running   0          7d2h
argocd-redis-584f4df7d7-7hfdq                        1/1     Running   0          7d2h
argocd-repo-server-55d56dd69f-fxqjt                  1/1     Running   1          7d2h
argocd-server-f7b574bc4-g7zp4                        1/1     Running   0          7d2h
```

**Comment by ThomsonSibiMukkada** [comment]
Still i have same issue in version 2.3.4 Argo and Kube version 1.23.3

**Comment by FlorianWenzel** [comment]
Just had the same issue, in my case it was because the project i selected did not have permissions to the repository.
I tried the "default" project which has all rights afaik, and that resolved it
