### PR TITLE
fix(webhook): bitbucket and azure not triggering refresh (#18289)

### LINKED ISSUE #9043: Only show commits with changes to path manifests only in history and rollback
Summary

In a monolith repository there is a lot of commits not related to the manifests path and some of these commits show up in history and rollback for an application.

Motivation

We are using a repository with both source code and manifests and that means most of the commits won't be related to the manifests but if I go to some application and click on history and rollback I would see non related commits although surprisingly not all commits(I don't know how this features decide which commit to include and which one not) which makes it confusing. 

Proposal

If there is a way we can tell the application to just include commits with changes to files in path only it would be much cleaner and helpful to use this feature.

### LINKED ISSUE #16255: ArgoCD triggers a refresh for all apps in same repo when webhook has empty commit
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.
* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.

**Describe the bug**

I am using a monorepo to store plain yaml manifests, every ArgoCD Application points to a specific folder in the monorepo (same  spec.source.repoURL)

I have a GitLab webhook setup on my monorepo and all the ArgoCD application have the following annotation to only trigger a refresh on the paths present in the commit 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  annotations:
    # resolves to the 'guestbook' directory
    argocd.argoproj.io/manifest-generate-paths: .
```

When a Gitlab payload is posted with an empty commit like this (payload truncated to only show relevant `commits` object):
```json
"commits": [
    {
      "id": "ddeae3fcb09c0d",
      "message": "empty commit\n",
      "title": "empty commit",
      "timestamp": "2023-11-06T20:01:41+00:00",
      "url": "https://gitlab.com/xxxxxxxx/-/commit/ddeae3fcb09c0d",
      "author": {
        "name": "xxxxxxx",
        "email": "[REDACTED]"
      },
      "added": [

      ],
      "modified": [

      ],
      "removed": [

      ]
    }
  ],
  "total_commits_count": 1,
```

ArgoCD will trigger a refresh for all apps from the repo and will not honor the `argocd.argoproj.io/manifest-generate-paths: .` annotation

**To Reproduce**

- Have at least 2 Applications with the  `argocd.argoproj.io/manifest-generate-paths: .`  annotation with the same spec.source.repoURL
- Make an empty commit on on the Gitlab repo triggering a webhook payloads
- ArgoCD will refresh both Apps not honoring the `argocd.argoproj.io/manifest-generate-paths: .`  annotation

**Expected behavior**

ArgoCD should only trigger a sync if the path is present in the `commits` payload object

**Version**

```shell
argocd: v2.8.5+85025e1
  BuildDate: 2023-10-28T00:13:42Z
  GitCommit: 85025e1dcb683b192ea3599de0b0a196d64c94a7
  GitTreeState: clean
  GoVersion: go1.20.10
  Compiler: gc
  Platform: windows/amd64
argocd-server: v2.8.4+ebab8ec
  BuildDate: 2023-10-30T19:24:59Z
  GitCommit: ebab8ec6259a6997fa3f310cddc539cb0c76b442
  GitTreeState: clean
  GoVersion: go1.20.10
  Compiler: gc
  Platform: linux/amd64
  ExtraBuildInfo: {Vendor Information: Red Hat OpenShift GitOps version: v1.10.1}
  Kustomize Version: v5.1.0 unknown
  Helm Version: v3.12.1+g1b5d1f0
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

### LINKED ISSUE #18289: Bug: Webhook trigger from Bitbucket does not refresh Applications in 2.11.0
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After the update from ArgoCD 2.10.9 to 2.11.0 the sync trigger on webhook from Bitbucket does not work anymore.

**To Reproduce**

1. Install ArgoCD 2.11.0
2. Connect a repository that is hosted in Bitbucket and create Application for that repo
3. Setup a webhook in Bitbucket to trigger ArgoCD https://argocd.cluster.../api/webhook
4. Push to bitbucket
5. Observe in ArgoCD that the application is not refreshed
6. perform a manual refresh to detect changes

**Expected behavior**

The refresh is triggered automatically.

**Version**

```shell
argocd: v2.11.0+d3f33c0
  BuildDate: 2024-05-07T16:01:41Z
  GitCommit: d3f33c00197e7f1d16f2a73ce1aeced464b07175
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
```

The version of Bitbucket is v8.19.3

**Logs**

```
time="2024-05-20T09:21:51Z" level=info msg="Received push event repo: ssh://git@git.domain.com:7999/incs/k8s-aws-eks-staging.git, revision: master, touchedHead: true"             
time="2024-05-20T09:21:51Z" level=info msg="Received push event repo: https://git.domain.com/scm/incs/k8s-aws-eks-staging.git, revision: master, touchedHead: true"                
```

Bitbucket receives HTTP 200 and the above log is shown in argocd-server

### PR DESCRIPTION
**Pull request by agaudreault**
Closes #18289
Closes https://github.com/argoproj/argo-cd/issues/16255 
Closes https://github.com/argoproj/argo-cd/issues/9043 

Some optimizations won't be available for all SCMs, but if the SCM does not implement the feature, it is better to cause a refresh.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by agaudreault** [comment]
This should be cherry picked in 2.11 and 2.12

**Review by ishitasequeira — APPROVED** [review]
LGTM!

**Review by pasha-codefresh — APPROVED** [review]
